spring:
  datasource:
    username: root
    password: root@1234
    url: jdbc:mysql://124.223.51.207:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false


mybatis:
  # 配置 Mapper 映射文件位置
  mapper-locations: classpath*:/mapper/**/*.xml
  # 别名包扫描路径，通过该属性可以给指定包中的类注册别名
  type-aliases-package: com.hua.entity
  configuration:
    # 开启自动驼峰命名规则(camel case)映射
    map-underscore-to-camel-case: true


#showSql
logging:
  level:
    com.hua.restfulstarter.domain.mapper: debug